name: CI

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Format check
        run: pnpm run fmt:check

      - name: Docs check
        run: pnpm run docs:update && git diff --exit-code README.md

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Compile
        run: pnpm run compile

      - name: Unit Tests
        run: xvfb-run -a pnpm run test:unit

      - name: Oxlint LSP Tests
        run: xvfb-run -a pnpm run test:oxlint && xvfb-run -a pnpm run test:oxlint-multi-root

      - name: Oxlint JS Plugin Test (flaky)
        continue-on-error: true
        run: xvfb-run -a pnpm run test:oxlint-js

      - name: Oxfmt LSP Tests
        run: xvfb-run -a pnpm run test:oxfmt

  test-windows:
    if: ${{ github.ref_name == 'main' }}
    name: Test (windows)
    runs-on: windows-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Compile
        run: pnpm run compile

      - name: Unit Tests
        run: pnpm run test:unit

      - name: Oxlint LSP Tests
        run: pnpm run test:oxlint && pnpm run test:oxlint-multi-root

      - name: Oxlint JS Plugin Test (flaky)
        continue-on-error: true
        run: pnpm run test:oxlint-js

      - name: Oxfmt LSP Tests
        run: pnpm run test:oxfmt
